/**
 * Criação das tabelas no BD
 */

DROP TABLE AVALIACAO_PRODUTO;
DROP TABLE FAVORITOS_PESSOA_FISICA;
DROP TABLE NOTIFICACOES;
DROP TABLE PRODUTO;
DROP TABLE MARCA_PRODUTO;
DROP TABLE PESSOA_JURIDICA;
DROP TABLE CATEGORIA_PRODUTO;
DROP TABLE CATEGORIA_LOJA;
DROP TABLE PESSOA;
DROP TABLE LOCALIZACAO;

ALTER TABLE PRODUTO ADD COLUMN IS_ACTIVE INTEGER NULL;
CREATE TABLE PESSOA(
ID_PESSOA INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
SOBRENOME VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
FOTO BLOB NULL,
EMAIL VARCHAR(100) NOT NULL
);
CREATE TABLE PESSOA_FISICA(
ID_PESSOA_FISICA INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
FK_PESSOA INTEGER NOT NULL,
ID_FACEBOOK LONG NOT NULL,
CPF VARCHAR(50) NULL,
FOREIGN KEY (FK_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);
CREATE TABLE CATEGORIA_LOJA
(
	ID_CATEGORIA_LOJA INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);
CREATE TABLE LOCALIZACAO
(
	ID_LOCALIZACAO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LONGITUDE  VARCHAR(300) NOT NULL,
	LATITUDE  VARCHAR(300) NOT NULL,
	CIDADE VARCHAR(100),
	ESTADO VARCHAR(100),
	BAIRRO VARCHAR(100)
);
CREATE TABLE PESSOA_JURIDICA(
ID_PESSOA_JURIDICA INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
FK_PESSOA INTEGER NOT NULL,
FK_CATEGORIA_LOJA INTEGER NOT NULL,
FK_LOCALIZACAO INTEGER NOT NULL,
SENHA VARCHAR(50) NOT NULL,
RAZAO_SOCIAL VARCHAR(50) NOT NULL,
CNPJ VARCHAR(50),
CODIGO_VERIFICACAO VARCHAR(4),
FOREIGN KEY (FK_PESSOA) REFERENCES PESSOA(ID_PESSOA),
FOREIGN KEY (FK_CATEGORIA_LOJA) REFERENCES CATEGORIA_LOJA(ID_CATEGORIA_LOJA),
FOREIGN KEY (FK_LOCALIZACAO) REFERENCES LOCALIZACAO(ID_LOCALIZACAO)
);

CREATE TABLE MARCA_PRODUTO
(
	ID_MARCA_PRODUTO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);
CREATE TABLE CATEGORIA_PRODUTO
(
	ID_CATEGORIA_PRODUTO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50)
);
CREATE TABLE PRODUTO
(
	ID_PRODUTO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FK_CATEGORIA_PRODUTO INTEGER NOT NULL,
	FK_MARCA_PRODUTO INTEGER NOT NULL,
	FK_PESSOA_JURIDICA INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(50),
	PRECO VARCHAR(50) NOT NULL,
	FOTO BLOB NOT NULL,
	DATA_PUBLICACAO TIMESTAMP NOT NULL,
	QTD_VISITA INTEGER NULL,
	IS_ACTIVE INTEGER,
	FOREIGN KEY (FK_CATEGORIA_PRODUTO) REFERENCES CATEGORIA_PRODUTO(ID_CATEGORIA_PRODUTO),
	FOREIGN KEY (FK_MARCA_PRODUTO) REFERENCES MARCA_PRODUTO(ID_MARCA_PRODUTO),
	FOREIGN KEY (FK_PESSOA_JURIDICA) REFERENCES PESSOA_JURIDICA(ID_PESSOA_JURIDICA)
);

UPDATE PRODUTO SET QTD_VISITA = 0 WHERE ID_PRODUTO = 1;

CREATE TABLE AVALIACAO_PRODUTO
(
	ID_AVALIACAO_PRODUTO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FK_PRODUTO INTEGER NOT NULL,
	FK_PESSOA_FISICA  INTEGER NOT NULL,
	COMENTARIO VARCHAR(50) NOT NULL,
	NOTA INTEGER NOT NULL,
	FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
	FOREIGN KEY (FK_PESSOA_FISICA) REFERENCES PESSOA_FISICA(ID_PESSOA_FISICA)
);
CREATE TABLE NOTIFICACOES
(
	ID_NOTIFICACOES INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FK_PRODUTO INTEGER NOT NULL,
	FK_PESSOA_JURIDICA  INTEGER NOT NULL,
	DETALHES VARCHAR(50) NOT NULL,
	FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
	FOREIGN KEY (FK_PESSOA_JURIDICA) REFERENCES PESSOA_JURIDICA(ID_PESSOA_JURIDICA)
);
CREATE TABLE FAVORITOS_PESSOA_FISICA
(
	ID_FAVORITOS INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FK_PESSOA_FISICA  INTEGER NOT NULL,
	FK_PRODUTO INTEGER NOT NULL,
	FOREIGN KEY (FK_PESSOA_FISICA) REFERENCES PESSOA_FISICA(ID_PESSOA_FISICA),
	FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)	
);

CREATE TABLE PRODUTOS_DESTAQUE
(
	ID_PRODUTOS_DESTAQUE INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FK_PRODUTO INTEGER NOT NULL,
	DATA_ENTRADA TIMESTAMP,
	DATA_SAIDA TIMESTAMP,
	EXPOSICAO INTEGER NOT NULL,
	FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)	
);


INSERT INTO LOCALIZACAO (LATITUDE, LONGITUDE) VALUES ('-25.514417','-49.124215');

INSERT INTO PESSOA (EMAIL, FOTO, TELEFONE, SOBRENOME, NOME) VALUES ('lucasgalvaonu@gmail.com',NULL,'5541996105002','Nunes','Lucas');

INSERT INTO CATEGORIA_LOJA (NOME) VALUES ('Eletrônicos');
INSERT INTO CATEGORIA_LOJA (NOME) VALUES ('Roupas');
INSERT INTO CATEGORIA_LOJA (NOME) VALUES ('Calçados');
INSERT INTO CATEGORIA_LOJA (NOME) VALUES ('Antiguario');
INSERT INTO CATEGORIA_LOJA (NOME) VALUES ('Papelari');

INSERT INTO PESSOA_JURIDICA(CNPJ,RAZAO_SOCIAL,SENHA,FK_LOCALIZACAO, FK_CATEGORIA_LOJA, FK_PESSOA)
VALUES ('42.520.171/0001-91','CIA ELETRO','LUC123',1,1,1);

commit;